__all__ = ['r2c']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['cyrlat', 'car', 'performConversion'])
@Js
def PyJsHoisted_performConversion_(lat, this, arguments, var=var):
    var = Scope({'lat':lat, 'this':this, 'arguments':arguments}, var)
    var.registers(['lat'])
    var.put('car', var.get('lat'))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/[hx]/g'), Js('х')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/a/g'), Js('а')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/b/g'), Js('б')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/v/g'), Js('в')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/g/g'), Js('г')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/d/g'), Js('д')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/e/g'), Js('е')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/[ëé]/g'), Js('ё')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/z/g'), Js('з')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ž/g'), Js('ж')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/зх/g'), Js('ж')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/i/g'), Js('и')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/j/g'), Js('й')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/k/g'), Js('к')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/l/g'), Js('л')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/m/g'), Js('м')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/n/g'), Js('н')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/o/g'), Js('о')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/p/g'), Js('п')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/r/g'), Js('р')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/s/g'), Js('с')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/t/g'), Js('т')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/u/g'), Js('у')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/f/g'), Js('ф')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/c/g'), Js('ц')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/č/g'), Js('ч')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/цх/g'), Js('ч')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/š/g'), Js('ш')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/сх/g'), Js('ш')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ŝ/g'), Js('щ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/шч/g'), Js('щ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/y/g'), Js('ы')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/[èê]/g'), Js('э')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/йу/g'), Js('ю')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/йа/g'), Js('я')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/û/g'), Js('ю')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/â/g'), Js('я')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/’/g'), Js('ь')))
    var.put('car', var.get('car').callprop('replace', JsRegExp("/'/g"), Js('ь')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ʹ/g'), Js('ь')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ʺ/g'), Js('ъ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ьь/g'), Js('ъ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/[HX]/g'), Js('Х')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/A/g'), Js('А')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/B/g'), Js('Б')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/V/g'), Js('В')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/G/g'), Js('Г')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/D/g'), Js('Д')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/E/g'), Js('Е')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ë/g'), Js('Ё')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Z/g'), Js('З')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ž/g'), Js('Ж')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ЗХ/g'), Js('Ж')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Зх/g'), Js('Ж')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/I/g'), Js('И')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/J/g'), Js('Й')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/K/g'), Js('К')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/L/g'), Js('Л')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/M/g'), Js('М')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/N/g'), Js('Н')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/O/g'), Js('О')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/P/g'), Js('П')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/R/g'), Js('Р')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/S/g'), Js('С')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/T/g'), Js('Т')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/U/g'), Js('У')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/F/g'), Js('Ф')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/C/g'), Js('Ц')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Č/g'), Js('Ч')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ЦХ/g'), Js('Ч')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Цх/g'), Js('Ч')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Š/g'), Js('Ш')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/СХ/g'), Js('Ш')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Сх/g'), Js('Ш')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Š/g'), Js('Щ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ШЧ/g'), Js('Щ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Шч/g'), Js('Щ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Y/g'), Js('Ы')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/[ÈÊ]/g'), Js('Э')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ЙУ/g'), Js('Ю')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ЙА/g'), Js('Я')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Йу/g'), Js('Ю')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Йа/g'), Js('Я')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Û/g'), Js('Ю')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Â/g'), Js('Я')))
    return var.get('car')
PyJsHoisted_performConversion_.func_name = 'performConversion'
var.put('performConversion', PyJsHoisted_performConversion_)
@Js
def PyJsHoisted_cyrlat_(cyr, this, arguments, var=var):
    var = Scope({'cyr':cyr, 'this':this, 'arguments':arguments}, var)
    var.registers(['cyr'])
    var.put('car', var.get('cyr'))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/а/g'), Js('a')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/б/g'), Js('b')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/в/g'), Js('v')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/г/g'), Js('g')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/д/g'), Js('d')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/е/g'), Js('e')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ё/g'), Js('ë')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ж/g'), Js('ž')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/з/g'), Js('z')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/и/g'), Js('i')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/й/g'), Js('j')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/к/g'), Js('k')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/л/g'), Js('l')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/м/g'), Js('m')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/н/g'), Js('n')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/о/g'), Js('o')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/п/g'), Js('p')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/р/g'), Js('r')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/с/g'), Js('s')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/т/g'), Js('t')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/у/g'), Js('u')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ф/g'), Js('f')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/х/g'), Js('h')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ц/g'), Js('c')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ч/g'), Js('č')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ш/g'), Js('š')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/щ/g'), Js('ŝ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ъ/g'), Js('ʺ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ы/g'), Js('y')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ь/g'), Js('ʹ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/э/g'), Js('è')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/ю/g'), Js('ju')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/я/g'), Js('ja')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/А/g'), Js('A')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Б/g'), Js('B')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/В/g'), Js('V')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Г/g'), Js('G')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Д/g'), Js('D')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Е/g'), Js('E')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ё/g'), Js('Ë')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ж/g'), Js('Ž')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/З/g'), Js('Z')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/И/g'), Js('I')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Й/g'), Js('J')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/К/g'), Js('K')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Л/g'), Js('L')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/М/g'), Js('M')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Н/g'), Js('N')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/О/g'), Js('O')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/П/g'), Js('P')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Р/g'), Js('R')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/С/g'), Js('S')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Т/g'), Js('T')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/У/g'), Js('U')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ф/g'), Js('F')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Х/g'), Js('H')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ц/g'), Js('C')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ч/g'), Js('Č')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ш/g'), Js('Š')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Щ/g'), Js('Ŝ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ъ/g'), Js('ʺ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ы/g'), Js('Y')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ь/g'), Js('ʹ')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Э/g'), Js('È')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Ю/g'), Js('Ju')))
    var.put('car', var.get('car').callprop('replace', JsRegExp('/Я/g'), Js('Ja')))
    return var.get('car')
PyJsHoisted_cyrlat_.func_name = 'cyrlat'
var.put('cyrlat', PyJsHoisted_cyrlat_)
pass
pass
pass
pass


# Add lib to the module scope
r2c = var.to_python()