__all__ = ['r2h']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['performConversion'])
@Js
def PyJsHoisted_performConversion_(input, this, arguments, var=var):
    var = Scope({'input':input, 'this':this, 'arguments':arguments}, var)
    var.registers(['input'])
    var.put('romanized', (var.get('input').callprop('toLowerCase')+Js(' ')))
    var.put('hangul', Js(''))
    var.put('initialjamovalue', (-Js(1.0)))
    var.put('medialjamovalue', (-Js(1.0)))
    var.put('finaljamovalue', (-Js(1.0)))
    var.put('pos', Js(0.0))
    while (var.get('pos')<var.get('romanized').get('length')):
        if (var.get('initialjamovalue')==(-Js(1.0))):
            var.put('len', var.get('maxlen'))
            if ((var.get('romanized').get('length')-var.get('pos'))<var.get('len')):
                var.put('len', (var.get('romanized').get('length')-var.get('pos')))
            while ((var.get('len')>Js(0.0)) and (var.get('initialjamovalue')==(-Js(1.0)))):
                if (var.get('initialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len'))))!=var.get(u"null")):
                    var.put('initialjamovalue', var.get('initialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len')))))
                    var.put('pos', var.get('len'), '+')
                (var.put('len',Js(var.get('len').to_number())-Js(1))+Js(1))
            if (var.get('initialjamovalue')==(-Js(1.0))):
                var.put('len', var.get('maxlen'))
                if ((var.get('romanized').get('length')-var.get('pos'))<var.get('len')):
                    var.put('len', (var.get('romanized').get('length')-var.get('pos')))
                while ((var.get('len')>Js(0.0)) and (var.get('medialjamovalue')==(-Js(1.0)))):
                    if (var.get('medialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len'))))!=var.get(u"null")):
                        var.put('medialjamovalue', var.get('medialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len')))))
                        var.put('pos', var.get('len'), '+')
                    (var.put('len',Js(var.get('len').to_number())-Js(1))+Js(1))
                if (var.get('medialjamovalue')!=(-Js(1.0))):
                    var.put('initialjamovalue', Js(11.0))
            if (var.get('initialjamovalue')==(-Js(1.0))):
                var.put('found', Js(False))
                var.put('len', var.get('maxlen'))
                if ((var.get('romanized').get('length')-var.get('pos'))<var.get('len')):
                    var.put('len', (var.get('romanized').get('length')-var.get('pos')))
                while ((var.get('len')>Js(0.0)) and var.get('found').neg()):
                    if (var.get('otherspecial').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len'))))!=var.get(u"null")):
                        var.put('hangul', var.get('otherspecial').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len')))), '+')
                        var.put('pos', var.get('len'), '+')
                        var.put('found', Js(True))
                    (var.put('len',Js(var.get('len').to_number())-Js(1))+Js(1))
                if var.get('found').neg():
                    var.put('hangul', var.get('romanized').callprop('charAt', var.get('pos')), '+')
                    (var.put('pos',Js(var.get('pos').to_number())+Js(1))-Js(1))
        else:
            if (var.get('medialjamovalue')==(-Js(1.0))):
                var.put('len', var.get('maxlen'))
                if ((var.get('romanized').get('length')-var.get('pos'))<var.get('len')):
                    var.put('len', (var.get('romanized').get('length')-var.get('pos')))
                while ((var.get('len')>Js(0.0)) and (var.get('medialjamovalue')==(-Js(1.0)))):
                    if (var.get('medialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len'))))!=var.get(u"null")):
                        var.put('medialjamovalue', var.get('medialjamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len')))))
                        var.put('pos', var.get('len'), '+')
                    (var.put('len',Js(var.get('len').to_number())-Js(1))+Js(1))
                if (var.get('medialjamovalue')==(-Js(1.0))):
                    var.put('hangul', var.get('romanized').callprop('charAt', (var.get('pos')-Js(1.0))), '+')
                    var.put('initialjamovalue', (-Js(1.0)))
            else:
                var.put('len', var.get('maxlen'))
                if ((var.get('romanized').get('length')-var.get('pos'))<var.get('len')):
                    var.put('len', (var.get('romanized').get('length')-var.get('pos')))
                while ((var.get('len')>Js(0.0)) and (var.get('finaljamovalue')==(-Js(1.0)))):
                    if (var.get('finaljamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len'))))!=var.get(u"null")):
                        var.put('finaljamovalue', var.get('finaljamo').get(var.get('romanized').callprop('substring', var.get('pos'), (var.get('pos')+var.get('len')))))
                        var.put('pos', var.get('len'), '+')
                    (var.put('len',Js(var.get('len').to_number())-Js(1))+Js(1))
                if (var.get('finaljamovalue')!=(-Js(1.0))):
                    var.put('hangul', var.get('String').callprop('fromCharCode', ((((var.get('initialjamovalue')*Js(588.0))+(var.get('medialjamovalue')*Js(28.0)))+var.get('finaljamovalue'))+Js(44032.0))), '+')
                else:
                    var.put('hangul', var.get('String').callprop('fromCharCode', (((var.get('initialjamovalue')*Js(588.0))+(var.get('medialjamovalue')*Js(28.0)))+Js(44032.0))), '+')
                var.put('initialjamovalue', (-Js(1.0)))
                var.put('medialjamovalue', (-Js(1.0)))
                var.put('finaljamovalue', (-Js(1.0)))
    return var.get('hangul').callprop('substring', Js(0.0), (var.get('hangul').get('length')-Js(1.0)))
PyJsHoisted_performConversion_.func_name = 'performConversion'
var.put('performConversion', PyJsHoisted_performConversion_)
var.put('initialjamo', var.get('Object').create())
var.get('initialjamo').put('b', Js(7.0))
var.get('initialjamo').put('bb', Js(8.0))
var.get('initialjamo').put('b̥', Js(7.0))
var.get('initialjamo').put('c', Js(12.0))
var.get('initialjamo').put('cc', Js(13.0))
var.get('initialjamo').put('ch', Js(14.0))
var.get('initialjamo').put('cʰ', Js(14.0))
var.get('initialjamo').put('cː', Js(13.0))
var.get('initialjamo').put('c̥', Js(12.0))
var.get('initialjamo').put('d', Js(3.0))
var.get('initialjamo').put('dd', Js(4.0))
var.get('initialjamo').put('d̥', Js(3.0))
var.get('initialjamo').put('g', Js(0.0))
var.get('initialjamo').put('gg', Js(1.0))
var.get('initialjamo').put('g̊', Js(0.0))
var.get('initialjamo').put('h', Js(18.0))
var.get('initialjamo').put('j', Js(12.0))
var.get('initialjamo').put('jh', Js(14.0))
var.get('initialjamo').put('jj', Js(13.0))
var.get('initialjamo').put('k', Js(0.0))
var.get('initialjamo').put('kh', Js(15.0))
var.get('initialjamo').put('kk', Js(1.0))
var.get('initialjamo').put('kʰ', Js(15.0))
var.get('initialjamo').put('kː', Js(1.0))
var.get('initialjamo').put('l', Js(5.0))
var.get('initialjamo').put('m', Js(6.0))
var.get('initialjamo').put('n', Js(2.0))
var.get('initialjamo').put('n̟', Js(2.0))
var.get('initialjamo').put('p', Js(7.0))
var.get('initialjamo').put('ph', Js(17.0))
var.get('initialjamo').put('pp', Js(8.0))
var.get('initialjamo').put('pʰ', Js(17.0))
var.get('initialjamo').put('pː', Js(8.0))
var.get('initialjamo').put('r', Js(5.0))
var.get('initialjamo').put('s', Js(9.0))
var.get('initialjamo').put('ss', Js(10.0))
var.get('initialjamo').put('sʰ', Js(10.0))
var.get('initialjamo').put('sː', Js(10.0))
var.get('initialjamo').put('t', Js(3.0))
var.get('initialjamo').put('tch', Js(13.0))
var.get('initialjamo').put('th', Js(16.0))
var.get('initialjamo').put('ts', Js(12.0))
var.get('initialjamo').put('tsh', Js(14.0))
var.get('initialjamo').put('tss', Js(13.0))
var.get('initialjamo').put('tt', Js(4.0))
var.get('initialjamo').put('tʰ', Js(16.0))
var.get('initialjamo').put('ɕ', Js(9.0))
var.get('initialjamo').put('ɾ', Js(5.0))
var.get('initialjamo').put("ch'", Js(14.0))
var.get('initialjamo').put('ch’', Js(14.0))
var.get('initialjamo').put("k'", Js(15.0))
var.get('initialjamo').put('k’', Js(15.0))
var.get('initialjamo').put("p'", Js(17.0))
var.get('initialjamo').put('p’', Js(17.0))
var.get('initialjamo').put("t'", Js(16.0))
var.get('initialjamo').put('t’', Js(16.0))
var.put('medialjamo', var.get('Object').create())
var.get('medialjamo').put('a', Js(0.0))
var.get('medialjamo').put('ae', Js(1.0))
var.get('medialjamo').put('ai', Js(1.0))
var.get('medialjamo').put('ay', Js(1.0))
var.get('medialjamo').put('e', Js(5.0))
var.get('medialjamo').put('eo', Js(4.0))
var.get('medialjamo').put('eu', Js(18.0))
var.get('medialjamo').put('eui', Js(19.0))
var.get('medialjamo').put('ey', Js(5.0))
var.get('medialjamo').put('i', Js(20.0))
var.get('medialjamo').put('ja', Js(2.0))
var.get('medialjamo').put('je', Js(3.0))
var.get('medialjamo').put('jo', Js(12.0))
var.get('medialjamo').put('ju', Js(17.0))
var.get('medialjamo').put('jɔ', Js(6.0))
var.get('medialjamo').put('jɛ', Js(7.0))
var.get('medialjamo').put('o', Js(8.0))
var.get('medialjamo').put('oe', Js(11.0))
var.get('medialjamo').put('oi', Js(11.0))
var.get('medialjamo').put('oy', Js(11.0))
var.get('medialjamo').put('u', Js(13.0))
var.get('medialjamo').put('ue', Js(10.0))
var.get('medialjamo').put('ui', Js(19.0))
var.get('medialjamo').put('uy', Js(19.0))
var.get('medialjamo').put('uɑ', Js(9.0))
var.get('medialjamo').put('uɔ', Js(14.0))
var.get('medialjamo').put('uɛ', Js(15.0))
var.get('medialjamo').put('wa', Js(9.0))
var.get('medialjamo').put('wae', Js(10.0))
var.get('medialjamo').put('wai', Js(10.0))
var.get('medialjamo').put('way', Js(10.0))
var.get('medialjamo').put('we', Js(15.0))
var.get('medialjamo').put('weo', Js(14.0))
var.get('medialjamo').put('wey', Js(15.0))
var.get('medialjamo').put('wi', Js(16.0))
var.get('medialjamo').put('wo', Js(14.0))
var.get('medialjamo').put('wu', Js(13.0))
var.get('medialjamo').put('wä', Js(10.0))
var.get('medialjamo').put('wø', Js(14.0))
var.get('medialjamo').put('wŏ', Js(14.0))
var.get('medialjamo').put('y', Js(16.0))
var.get('medialjamo').put('ya', Js(2.0))
var.get('medialjamo').put('yae', Js(3.0))
var.get('medialjamo').put('yai', Js(3.0))
var.get('medialjamo').put('yay', Js(3.0))
var.get('medialjamo').put('ye', Js(7.0))
var.get('medialjamo').put('yeo', Js(6.0))
var.get('medialjamo').put('yey', Js(7.0))
var.get('medialjamo').put('yo', Js(12.0))
var.get('medialjamo').put('yu', Js(17.0))
var.get('medialjamo').put('yä', Js(3.0))
var.get('medialjamo').put('yø', Js(6.0))
var.get('medialjamo').put('yŏ', Js(6.0))
var.get('medialjamo').put('ä', Js(1.0))
var.get('medialjamo').put('ö', Js(11.0))
var.get('medialjamo').put('ø', Js(4.0))
var.get('medialjamo').put('ŏ', Js(4.0))
var.get('medialjamo').put('ŭ', Js(18.0))
var.get('medialjamo').put('ŭi', Js(19.0))
var.get('medialjamo').put('ɑ', Js(0.0))
var.get('medialjamo').put('ɔ', Js(4.0))
var.get('medialjamo').put('ɛ', Js(5.0))
var.get('medialjamo').put('ɨ', Js(18.0))
var.get('medialjamo').put('ɨi', Js(19.0))
var.get('medialjamo').put('ɯ', Js(18.0))
var.get('medialjamo').put('ʉ', Js(18.0))
var.get('medialjamo').put('ʉi', Js(19.0))
var.put('finaljamo', var.get('Object').create())
var.get('finaljamo').put('b', Js(17.0))
var.get('finaljamo').put('bs', Js(18.0))
var.get('finaljamo').put('b̥', Js(17.0))
var.get('finaljamo').put('c', Js(22.0))
var.get('finaljamo').put('ch', Js(23.0))
var.get('finaljamo').put('cʰ', Js(23.0))
var.get('finaljamo').put('c̥', Js(22.0))
var.get('finaljamo').put('d', Js(7.0))
var.get('finaljamo').put('d̥', Js(7.0))
var.get('finaljamo').put('g', Js(1.0))
var.get('finaljamo').put('gg', Js(2.0))
var.get('finaljamo').put('gs', Js(3.0))
var.get('finaljamo').put('g̊', Js(1.0))
var.get('finaljamo').put('h', Js(27.0))
var.get('finaljamo').put('j', Js(22.0))
var.get('finaljamo').put('jh', Js(23.0))
var.get('finaljamo').put('k', Js(1.0))
var.get('finaljamo').put('kh', Js(24.0))
var.get('finaljamo').put('kk', Js(2.0))
var.get('finaljamo').put('ks', Js(3.0))
var.get('finaljamo').put('kʰ', Js(24.0))
var.get('finaljamo').put('kː', Js(2.0))
var.get('finaljamo').put('l', Js(8.0))
var.get('finaljamo').put('lb', Js(11.0))
var.get('finaljamo').put('lg', Js(9.0))
var.get('finaljamo').put('lh', Js(15.0))
var.get('finaljamo').put('lk', Js(9.0))
var.get('finaljamo').put('lm', Js(10.0))
var.get('finaljamo').put('lp', Js(11.0))
var.get('finaljamo').put('lph', Js(14.0))
var.get('finaljamo').put('lpʰ', Js(14.0))
var.get('finaljamo').put('ls', Js(12.0))
var.get('finaljamo').put('lt', Js(13.0))
var.get('finaljamo').put('lth', Js(13.0))
var.get('finaljamo').put('ltʰ', Js(13.0))
var.get('finaljamo').put('m', Js(16.0))
var.get('finaljamo').put('n', Js(4.0))
var.get('finaljamo').put('nc', Js(5.0))
var.get('finaljamo').put('nch', Js(6.0))
var.get('finaljamo').put('ncʰ', Js(6.0))
var.get('finaljamo').put('ng', Js(21.0))
var.get('finaljamo').put('nh', Js(6.0))
var.get('finaljamo').put('nj', Js(5.0))
var.get('finaljamo').put('nɟ', Js(5.0))
var.get('finaljamo').put('n̟', Js(4.0))
var.get('finaljamo').put('p', Js(17.0))
var.get('finaljamo').put('ph', Js(26.0))
var.get('finaljamo').put('ps', Js(18.0))
var.get('finaljamo').put('pʰ', Js(26.0))
var.get('finaljamo').put('r', Js(8.0))
var.get('finaljamo').put('s', Js(19.0))
var.get('finaljamo').put('ss', Js(20.0))
var.get('finaljamo').put('sʰ', Js(20.0))
var.get('finaljamo').put('sː', Js(20.0))
var.get('finaljamo').put('t', Js(7.0))
var.get('finaljamo').put('th', Js(25.0))
var.get('finaljamo').put('ts', Js(22.0))
var.get('finaljamo').put('tsh', Js(23.0))
var.get('finaljamo').put('tʰ', Js(25.0))
var.get('finaljamo').put('ŋ', Js(21.0))
var.get('finaljamo').put('ɕ', Js(19.0))
var.get('finaljamo').put('ɾ', Js(8.0))
var.get('finaljamo').put("ch'", Js(23.0))
var.get('finaljamo').put('ch’', Js(23.0))
var.get('finaljamo').put("k'", Js(24.0))
var.get('finaljamo').put('k’', Js(24.0))
var.get('finaljamo').put("p'", Js(26.0))
var.get('finaljamo').put('p’', Js(26.0))
var.get('finaljamo').put("t'", Js(25.0))
var.get('finaljamo').put('t’', Js(25.0))
var.put('otherspecial', var.get('Object').create())
var.get('otherspecial').put('-', Js(''))
var.get('otherspecial').put('\\-', Js('-'))
var.get('otherspecial').put('.', Js(''))
var.get('otherspecial').put('\\.', Js('.'))
var.put('maxlen', Js(3.0))
pass
pass


# Add lib to the module scope
r2h = var.to_python()